"""empty message

Revision ID: 920a17466d6b
Revises: 2a8c81def04a
Create Date: 2026-02-17 15:32:28.388192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920a17466d6b'
down_revision = '2a8c81def04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_city', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'location', ['location_city'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_city')

    op.drop_table('location')
    # ### end Alembic commands ###
